Major Refactor
TaskMaster873/DRFWClient pull request #187
Opened 2023-02-20 21:09 UTC by BlobMaster41

Major refactor!

2023-02-20 21:11 UTC, DJLawton commented on .editorconfig
> +end_of_line = lf
crlf. On est en Windows pas linux.

2023-02-20 21:14 UTC, DJLawton commented on src/src/engine/RoutesPath.ts
> +    EMPLOYEE_WITH_PARAM = '/:id/employee',
should be /departments/:id/employees

2023-02-20 21:36 UTC, DJLawton commented on src/src/engine/pages/AddEmployee.tsx
> +                onDataChange={this.addEmployee.bind(this)}
to unbind to callback

2023-02-20 21:39 UTC, DJLawton commented on src/src/engine/pages/Employees.tsx
> +class Employees extends React.Component<EmployeeProps, EmployeeState> {
EmployeesInternal au lieu de Employees

2023-02-20 21:40 UTC, DJLawton commented on src/src/engine/pages/ResetPassword.tsx
> +        return <Navigate to="/forgot-password"></Navigate>;
useNavigate here

2023-02-20 21:43 UTC, VillyGH requested changes

2023-02-20 21:43 UTC, VillyGH commented on src/src/engine/components/ComponentAvailabilities.tsx
> +interface ComponentAvailabilitiesProps {
À déplacer

2023-02-20 21:43 UTC, VillyGH commented on src/src/engine/components/ComponentAvailabilities.tsx
> +interface ComponentAvailabilitiesState {
À déplacer

2023-02-20 21:43 UTC, VillyGH commented on src/src/engine/components/ComponentAvailabilities.tsx
> +interface DayPilotArgumentTimeRange {
À déplacer

2023-02-20 21:43 UTC, DJLawton approved these changes
looks good

2023-02-20 21:43 UTC, RominMartignat approved these changes

2023-02-20 21:47 UTC, merged

2023-02-23 16:47 UTC, blemelin commented on src/src/engine/Engine.tsx
> +                            <Route path={RoutesPath.INDEX} element={<Index/>}/>
Les constantes pour les routes, c'est une excellente idée,

2023-02-23 16:47 UTC, blemelin commented on src/src/engine/api/APIManager.ts
> +    private requestUserCreationFromWorker(employee: EmployeeCreateDTO, password: string): Promise<CreatedAccountData> {
Je remarque plusieurs choses dans ce fichier :

* Certaines méthodes sont documentées, d'autres non. Je comprends pas votre standard : qu'est-ce que vous documentez finalement ?
* Les méthodes sont complètement en désordre. Par exemple, il y a une fonction `getEmployeeName` entre `listenWorkerEvents` et `onEvent`. Je vous conseille fortement de regrouper les méthodes ayant le même objectif ensemble.
* Certaines méthodes pourraient être privées. C'est le cas de `getErrorMessageFromCode`.

2023-02-23 16:47 UTC, blemelin commented on src/src/engine/api/APIManager.ts
> +    public async deactivateEmployee(employeeId: string | null): Promise<string | null> {
Pourquoi est-ce que ce paramètre serait nullable ? Je comprends mal comment tu pourais désactiver un employé null.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/components/ComponentAbout.tsx
> -// @ts-ignore
Ce `ts-ignore` peux être réglé en créant un fichier `react-app-env.d.ts` dans le dossier `src` contenant `/// <reference types="react-scripts" />`. Ensuite, enlève le fichier `index.d.ts` ainsi que le fichier `logo.png.d.ts`.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/components/ComponentAbout.tsx
> +                    src={Logo as any}
Voir mon commentaire précédent. Vous pourrez ensuite enlever le `as any`.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/components/ComponentAddEmployee.tsx
> +import { AddEmployeeProps, Employee, EmployeeCreateDTO } from "../types/Employee";
`AddEmployeeProps` devrait probablement être dans ce fichier, au lieu d'être dans un fichier à part, étant donné qu'il n'est utilisé qu'ici à première vue.

Vous l'avez fait dans `ComponentAddDepartement`.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/components/ComponentAvailabilities.tsx
> +    private calendarRef: React.RefObject<any> = React.createRef();
Tu peux remplacer le `any` par `DayPilotCalendar`.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/components/ComponentAvailabilities.tsx
> +    private datePickerRef: React.RefObject<any> = React.createRef();
... et ici, par `DayPilotNavigator`.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/components/ComponentAvailabilities.tsx
> -    onEventClick = async (args: any) => { // TODO changer ce que la méthode fait
J'ai pas trouvé où c'était utilisé. Est-ce que cette fonction sert encore ?

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/components/ComponentChangePassword.tsx
>  import Logo from "../../deps/images/logo.png";
Voici un `ts-ignore` à enlever, comme j'ai précisé plus haut.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/messages/APIMessages.ts
>      employeeAlreadyExists: "L'emploi est déjà existant",
Je suis pas mal certain que vous avez dit vouloir utiliser du `SCREAMING_CASE` pour le nommage de vos constantes. Vous en avez fait quelques unes ici, mais pas toutes. Continuez de faire le suivi de ce dossier.

2023-02-23 21:45 UTC, blemelin commented on src/src/engine/pages/AddEmployee.tsx
> +        let params: [
Tu peux faire une déstructuration du tableau afin d'éviter d'accéder aux éléments par leurs index :

```ts
let [departements, roles, titles] = await Promise.all([departmentsPromise, rolesPromise, titlesPromise]);
```

2023-02-24 14:32 UTC, blemelin commented on src/src/engine/pages/CreateSchedule.tsx
> +        if (Array.isArray(listData)) {
Je pense pas me tromper en disant que cette condition est toujours vraie.

2023-02-24 14:32 UTC, blemelin commented on src/src/engine/pages/CreateSchedule.tsx
> +            switch (length) {
Un `switch case` pour deux cas. Il me semble que cela avait été identifié dans la review.

2023-02-24 14:32 UTC, blemelin commented on src/src/engine/components/ComponentScheduleCreate.tsx
> +	listOfShifts: Shift[];
Parfois, dans votre code, vous nommez vos tableaux avec une forme au pluriel (`events`, `shifts`, `employees`, ...) et d'autres fois, vous préfixez le nom de `listOf` (comme montré ici). Faudra choisir quelle forme vous désirez (j'ai une préférence pour la forme au pluriel).

2023-02-24 14:32 UTC, blemelin commented on src/src/engine/pages/Departments.tsx
> +    public addDepartment = async (department: Department) : Promise<void> => {
N'a pas à être public.

2023-02-24 14:32 UTC, blemelin commented on src/src/engine/pages/Employees.tsx
> +export function EmployeeWrapper(): any {
Remplacez ce `any` par `JSX.Element`.

2023-02-24 14:32 UTC, blemelin commented on src/src/engine/pages/Employees.tsx
> +class EmployeesInternal extends React.Component<EmployeeProps, EmployeeState> {
Je comprends pas pourquoi `EmployeeProps` est dans un autre fichier vu que `EmployeeState` est ici.