Update schedule creator
TaskMaster873/DRFWClient pull request #202
Opened 2023-02-24 21:54 UTC by DJLawton

2023-02-24 22:52 UTC, DJLawton commented
J'su mad, ça marche pas.

2023-02-27 14:23 UTC, RominMartignat approved these changes
good

2023-02-27 14:27 UTC, BlobMaster41 requested changes
Looks good

2023-02-27 14:27 UTC, BlobMaster41 commented on src/__tests__/testComponentPopupSchedule.test.js
> -  /* test("test user add a different color in the color input, should change de value of the input", async () => {
useless code?

2023-02-27 14:42 UTC, merged