Availabilitiespopup for create
TaskMaster873/DRFWClient pull request #215
Opened 2023-03-02 21:03 UTC by RominMartignat

2023-03-02 21:06 UTC, DJLawton commented on firestore.rules
> +                allow delete: if(isValidUnavailabilityDelete());
`allow read: if isValidToReadUnavailabilities() ;
 allow write: if isValidUnavailabilityCreate();
 allow delete: if isValidUnavailabilityDelete();`

Also, missing validation functions. Called but not declared.

2023-03-02 21:07 UTC, DJLawton commented on firestore.rules
> +            }
Insufficient validation. Should check if the requester's uid matched the Unavailabilities' employeeId

2023-03-02 21:08 UTC, DJLawton commented on src/src/engine/api/APIManager.ts
> +                            });
Do this operation in a batched write [Batched write doc](https://firebase.google.com/docs/firestore/manage-data/transactions)

2023-03-02 21:09 UTC, DJLawton commented on src/src/engine/api/APIManager.ts
> +                list.recursiveExceptions = listOfRecursive;
Traditional `for(let variable of variables)` is prefered over forEach

2023-03-02 21:11 UTC, DJLawton commented on src/src/engine/api/APIManager.ts
> +    public async getOneEmployeeUnavailabilities(idEmployee?: string): Promise<EmployeeAvailabilities | null> {
Why is idEmployee optional? Should be necessary if you're getting one employee's unavailabilities

2023-03-03 15:43 UTC, VillyGH commented on firestore.rules
>                  allow read;
À faire

2023-03-03 15:48 UTC, VillyGH requested changes

2023-03-03 15:48 UTC, VillyGH commented on src/src/engine/api/APIManager.ts
> +    private async checkUnavailabilityAlreadyExists(list: EmployeeAvailabilitiesForCreate): Promise<unknown | null> {
Utiliser la méthode déjà existante dans APIUtils checkIfAlreadyExists

2023-03-03 15:48 UTC, VillyGH commented on src/src/engine/api/APIManager.ts
> +            return null;
retourner EmployeeAvailabilities? et enlever le else

2023-03-03 15:48 UTC, VillyGH commented on src/src/engine/types/EmployeeAvailabilities.ts
> +    /** When he cannot work */
à mettre dans la Doc au dessus et non en dessous

2023-03-03 15:50 UTC, RominMartignat commented on firestore.rules
>                  allow read;
déjà fait

2023-03-03 15:55 UTC, BlobMaster41 requested changes

2023-03-03 15:55 UTC, BlobMaster41 commented on src/src/engine/api/APIManager.ts
> +     *
essaie de follow le schema de commentaire que on as mis en place si possible

2023-03-03 15:55 UTC, BlobMaster41 commented on src/src/engine/api/APIManager.ts
> +                    console.log("data", data);
peut-etre enlevé

2023-03-03 15:55 UTC, BlobMaster41 commented on src/src/engine/components/ComponentAvailabilities.tsx
> +        console.log(events);
peut-être enlevé

2023-03-03 15:55 UTC, BlobMaster41 commented on src/src/engine/pages/Availabilities.tsx
> +        console.log(this.state);
peut-être enlevé

2023-03-03 15:55 UTC, BlobMaster41 commented on src/src/engine/pages/Availabilities.tsx
> +            console.log(canRenderData);
peut-être enlevé

2023-03-03 15:55 UTC, BlobMaster41 commented on src/src/engine/types/EmployeeAvailabilities.ts
> +	}
juste une petite erreur de tablature (syntax). Tu as mis une tab je pense

2023-03-03 19:55 UTC, DJLawton approved these changes
looks good

2023-03-03 19:55 UTC, merged